/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blockchain.h"

bool_t
xdr_tipo_salida (XDR *xdrs, tipo_salida *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->cant_ceros))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->texto, 256))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->inicio))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->final))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado_hash (XDR *xdrs, resultado_hash *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->relleno))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->encontrado))
		 return FALSE;
	return TRUE;
}
